import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#e8fbff",
        "surface": "#0e0e0e",
        "on-background": "#ffffff",
        "on-surface-variant": "#adaaaa",
        "tertiary-fixed-dim": "#f0f1f1",
        "surface-container-highest": "#262626",
        "on-primary": "#586500",
        "background": "#0e0e0e",
        "on-tertiary": "#5e5f60",
        "on-secondary": "#004d57",
        "error": "#ff7351",
        "error-dim": "#d53d18",
        "on-surface": "#ffffff",
        "secondary-fixed-dim": "#00d7f0",
        "on-primary-fixed-variant": "#5a6700",
        "on-primary-fixed": "#3f4900",
        "on-secondary-fixed": "#003a42",
        "error-container": "#b92902",
        "secondary": "#00e3fd",
        "on-error": "#450900",
        "surface-container": "#1a1919",
        "outline": "#777575",
        "outline-variant": "#494847",
        "primary-fixed-dim": "#ceea00",
        "tertiary-fixed": "#ffffff",
        "surface-variant": "#262626",
        "surface-bright": "#2c2c2c",
        "on-primary-container": "#505c00",
        "on-error-container": "#ffd2c8",
        "secondary-container": "#006875",
        "surface-container-low": "#131313",
        "on-tertiary-fixed": "#4f5051",
        "on-tertiary-fixed-variant": "#6c6d6e",
        "surface-container-high": "#201f1f",
        "primary-fixed": "#dbf900",
        "inverse-primary": "#586500",
        "primary-container": "#dbf900",
        "tertiary-dim": "#ebebeb",
        "secondary-fixed": "#26e6ff",
        "secondary-dim": "#00d4ec",
        "tertiary": "#f9f9f9",
        "inverse-surface": "#fcf8f8",
        "on-tertiary-container": "#555757",
        "surface-container-lowest": "#000000",
        "inverse-on-surface": "#565554",
        "tertiary-container": "#ebebeb",
        "on-secondary-fixed-variant": "#005964",
        "primary-dim": "#d0ed00",
        "primary": "#f6ffbf",
        "surface-dim": "#0e0e0e",
        "surface-tint": "#f6ffbf",
      },
      borderRadius: {
        "none": "0px",
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
